/**
 * Bundled chain-restaurant database — search + detail, with no network call.
 *
 * The restaurant half of `searchFoods` / `getFoodDetail`, and a deliberate
 * sibling of `usda-db.ts` rather than an extension of it (ADR-0027). The
 * dataset (`functions/data/restaurant-foods.json`, ~4.3 MB, 25,216 items across
 * 91 chains) is generated by `scripts/ingest-menustat.mjs` from MenuStat's 2022
 * annual snapshot and committed, so a deploy carries its own data: no API key,
 * no rate ceiling, no upstream — the same economics ADR-0018 bought for USDA.
 *
 * ── Why a sibling and not the same index ──
 * USDA foods are per-100 g with household portions, named as comma-delimited
 * descriptor lists ("Egg, whole, raw"). Restaurant items are per-SERVING
 * absolutes with a brand attached and are named as menu copy ("Chick-fil-A
 * Chicken Sandwich"). `usda-db.ts`'s scorer is tuned hard for the first shape —
 * its PLAIN / PROCESSED / COMPOSITE heuristics exist to keep a bare ingredient
 * query off the recipes that mention it, which is exactly the wrong instinct
 * here, where the dish IS the answer. Sharing the index would mean weakening
 * both. `words` and `stem` ARE reused, so the two tokenize identically.
 *
 * ── The gram-weight problem, and why `grams` can be 0 ──
 * MenuStat published no serving weight for 15,077 of these items (60%), and
 * dropping them would delete IHOP, The Cheesecake Factory, Wendy's, Taco Bell,
 * Chili's and Olive Garden from the corpus outright — six of the fifteen chains
 * the owner named. So they ship with `grams: 0`, meaning "one serving, weight
 * not published". That value is safe on every client already in the field:
 * mobile's `FoodSearch` guards `s.grams > 0` before using it (since 2026-07-01,
 * so it is in every shipped binary), `custom-food.ts` writes
 * `servingUnit: 'serving'` when grams is absent, and `meal-utterance.ts` guards
 * on it being falsy. The web client's `food-search.component.ts` was the ONE
 * place that used it unguarded; that is fixed alongside this module.
 *
 * WIRE CONTRACT: `FoodSearchHit` / `ServingOption` / `FoodDetail` are the shapes
 * defined in `./food-search.ts`, which mirrors `packages/core/src/food-search.ts`
 * by hand. This module produces those shapes and must not diverge from them.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { stem, words } from "./usda-db";

/** One restaurant item as emitted by the ingest. Macros are per SERVING — not
 *  per 100 g, which is the load-bearing difference from `UsdaFood`. */
export interface MenuStatItem {
  id: string;
  chain: string;
  desc: string;
  /** What MenuStat's `item_description` adds beyond the name — the menu section
   *  and any qualifier ("Kids Sides", "Available In: Boneless Wings"). Matched
   *  on but not displayed: it is useful for finding an item and noisy to read.
   *  Absent when the description said nothing the name did not. */
  note?: string;
  cat: string;
  kcal: number;
  protein: number;
  carb?: number;
  fat?: number;
  /** Grams the published serving weighs, or 0 when MenuStat published none. */
  grams: number;
  /** Display label for the serving: "1 Bowl", "183 g", or "1 serving". */
  label: string;
}

export interface MenuStatFile {
  year: number;
  source: string;
  items: MenuStatItem[];
}

/** An item plus the lowercased forms the matcher needs, computed once at load. */
export interface IndexedMenuItem extends MenuStatItem {
  chainNorm: string;
  /** Chain name with every non-alphanumeric character removed, so a query for
   *  "chickfila" or "mcdonalds" reaches "Chick Fil A" / "McDonald's". */
  chainTight: string;
  chainWords: string[];
  descWords: string[];
  descStems: string[];
  descNorm: string;
}

export interface MenuStatServingOption {
  label: string;
  grams: number;
  kcal: number;
  protein: number;
  carbs?: number;
  fat?: number;
  kind: "per100g" | "portion";
}

export interface MenuStatHit {
  source: "menu";
  id: string;
  description: string;
  brand: string;
  dataType: string;
  servings: MenuStatServingOption[];
}

export interface MenuStatDetail {
  source: "menu";
  id: string;
  description: string;
  brand: string;
  servings: MenuStatServingOption[];
}

export interface MenuStatIndex {
  year: number;
  items: IndexedMenuItem[];
  /** Every chain, tokenized once, longest first — so "jack in the box" is
   *  tested before "jack" could match some other chain's word. */
  chains: { name: string; tight: string; words: string[] }[];
}

/**
 * Categories a bare food query almost never means. Someone typing "chipotle
 * chicken" wants the bowl, not the packet of dressing that also says chicken.
 * Small on purpose — a demotion, never an exclusion, exactly as `usda-db.ts`
 * treats its vague-marker family.
 */
const CATEGORY_PENALTY: Record<string, number> = {
  "Toppings & Ingredients": 14,
  Beverages: 6,
};

/**
 * Ordering for a BARE chain query — "olive garden" with nothing after it.
 *
 * Every item then scores identically on relevance (they all match the chain and
 * there are no other tokens), so without this the tie is broken by name length
 * and the chain's page opens on "Asparagus", "Coleslaw" and "Grapes". MenuStat
 * publishes no popularity signal, so the honest proxy is what kind of thing it
 * is: someone browsing a restaurant is looking for a meal first and a garnish
 * last. Applied ONLY when the query is a bare chain name — once the user has
 * typed anything else, that text is a better signal than this table.
 */
const BARE_CHAIN_CATEGORY_ORDER = [
  "Entrees",
  "Sandwiches",
  "Burgers",
  "Pizza",
  "Salads",
  "Soup",
  "Appetizers & Sides",
  "Fried Potatoes",
  "Baked Goods",
  "Desserts",
  "Beverages",
  "Toppings & Ingredients",
];
const BARE_CHAIN_CATEGORY_BONUS = new Map(
  BARE_CHAIN_CATEGORY_ORDER.map((cat, i) => [cat, (BARE_CHAIN_CATEGORY_ORDER.length - i) * 4]),
);

/**
 * Every form of a chain name worth matching.
 *
 * Two per chain, because dropping a leading article is necessary but not
 * sufficient. "The Cheesecake Factory" is typed "cheesecake factory" essentially
 * always, so the stripped form has to exist — without it the chain goes
 * unrecognised and its 552 items lose their page. But "Jack in the Box" carries
 * a MEDIAL "the" that people do type, so the full form has to survive too.
 * Generating both is cheaper than a rule that tells the positions apart, and it
 * cannot get the distinction wrong.
 *
 * Mirrored by `ENTRIES` in `packages/core/src/restaurant-chains.ts`, which the
 * mobile client uses to decide whether to ask the server at all.
 */
function chainForms(name: string, chainWords: string[]): { name: string; tight: string; words: string[] }[] {
  const stripped = chainWords[0] === "the" ? chainWords.slice(1) : chainWords;
  const forms = [{ name, tight: chainWords.join(""), words: chainWords }];
  if (stripped !== chainWords && stripped.length) {
    forms.push({ name, tight: stripped.join(""), words: stripped });
  }
  return forms;
}

/** Awarded when every word of a chain name appears in the query. This is the
 *  strongest intent signal the search has — "taco bell" is not ambiguous — and
 *  it is what makes an exact chain match outrank generic FDC results (ADR-0027
 *  decision point 3). */
const CHAIN_MATCH_BONUS = 500;

const MAX_DESCRIPTION = 140;

let cache: MenuStatIndex | null = null;

function tighten(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]/g, "");
}

/** Index raw ingest records for matching. Exported for tests. */
export function indexMenuItems(file: MenuStatFile): MenuStatIndex {
  const items: IndexedMenuItem[] = file.items.map((i) => {
    // The note joins the searchable text so "fries basket kids" and "applebees
    // boneless wings" reach the right row, while `desc` stays the clean menu
    // name the picker renders.
    const searchable = i.note ? `${i.desc} ${i.note}` : i.desc;
    const w = words(searchable);
    return {
      ...i,
      chainNorm: i.chain.toLowerCase(),
      chainTight: tighten(i.chain),
      chainWords: words(i.chain),
      descWords: w,
      descStems: w.map(stem),
      descNorm: searchable.toLowerCase(),
    };
  });

  const seen = new Set<string>();
  const chains: { name: string; tight: string; words: string[] }[] = [];
  for (const i of items) {
    if (seen.has(i.chain)) continue;
    seen.add(i.chain);
    chains.push(...chainForms(i.chain, i.chainWords));
  }
  chains.sort((a, b) => b.words.length - a.words.length);
  return { year: file.year, items, chains };
}

/**
 * Load and index the bundled dataset, once per function instance. `__dirname`
 * is `functions/lib` after tsc, so the data sits one level up — same as
 * `loadFoods`.
 */
export function loadRestaurantFoods(
  dataPath = join(__dirname, "../data/restaurant-foods.json"),
): MenuStatIndex {
  if (!cache) {
    cache = indexMenuItems(JSON.parse(readFileSync(dataPath, "utf8")) as MenuStatFile);
  }
  return cache;
}

/** Test seam: drop the memoized dataset. */
export function resetMenuCache(): void {
  cache = null;
}

/**
 * Find the chain a query names, if any, and return the query tokens that are
 * left over once its name is consumed.
 *
 * Returns `null` when no chain is named — which is the common case and the
 * reason restaurant results do not swamp a query like "banana".
 *
 * The tight form is tested first so "chickfila" and "mcdonalds" — how people
 * actually type these — reach chains whose stored names are "Chick Fil A" and
 * "McDonald's".
 */
export function matchChain(
  index: MenuStatIndex,
  queryWords: string[],
): { chain: string; rest: string[] } | null {
  const tightQuery = queryWords.join("");
  for (const c of index.chains) {
    // Whole-name match against the punctuation-free query ("chickfila").
    if (c.tight.length >= 4 && tightQuery.includes(c.tight)) {
      const rest = queryWords.filter((w) => !c.tight.includes(w));
      return { chain: c.name, rest };
    }
  }
  for (const c of index.chains) {
    // Word-wise match: every word of the chain name appears in the query.
    if (c.words.length && c.words.every((w) => queryWords.includes(w))) {
      const rest = queryWords.filter((w) => !c.words.includes(w));
      return { chain: c.name, rest };
    }
  }
  return null;
}

/**
 * Score one item against the query tokens, or null when it doesn't match.
 *
 * Every token must appear somewhere in the chain name or the item name, so
 * "taco bell burrito" cannot match a Taco Bell drink. Beyond that the score
 * rewards how each token matched — whole word beats prefix beats substring —
 * then favours short names, which are the headline menu items rather than the
 * build-your-own permutations.
 */
export function scoreItem(item: IndexedMenuItem, tokens: string[], namedChain: string | null): number | null {
  if (!tokens.length && !namedChain) return null;
  if (namedChain && item.chain !== namedChain) return null;

  let score = namedChain ? CHAIN_MATCH_BONUS : 0;

  // A bare chain name leaves nothing to rank on — see BARE_CHAIN_CATEGORY_ORDER.
  if (namedChain && !tokens.length) {
    score += BARE_CHAIN_CATEGORY_BONUS.get(item.cat) ?? 0;
  }

  for (const token of tokens) {
    const t = stem(token);
    let best = 0;
    if (item.descWords.includes(token) || item.descStems.includes(t)) best = 10;
    else if (item.descWords.some((w) => w.startsWith(token)) || item.descStems.some((w) => w.startsWith(t))) best = 6;
    else if (item.descNorm.includes(token)) best = 3;
    // Matching the CHAIN on a query that did not name one is a weak signal and
    // must not outrank matching the item: "chicken sandwich" should lead with a
    // sandwich, not with any item from Church's Chicken.
    else if (!namedChain && (item.chainWords.includes(token) || item.chainTight.includes(token))) best = 4;
    if (!best) return null;
    score += best;
  }

  score -= CATEGORY_PENALTY[item.cat] ?? 0;
  // Shorter names win ties: "Chicken Sandwich" over "Chicken Sandwich Meal with
  // Waffle Fries and a Large Drink".
  score -= Math.min(item.descWords.length, 20) * 0.5;
  // An item with a published weight is strictly more useful than one without,
  // because the client can scale it. Tiny — it must never outrank relevance.
  if (item.grams > 0) score += 1;

  return score;
}

/** Build the portion picker for one item.
 *
 * MenuStat publishes exactly ONE serving per item, so there is one row — plus a
 * `per100g` row when a gram weight exists, which is what a metric user's unit
 * preference sorts to the top. No row is synthesized when the weight is absent:
 * a fabricated 100 g figure for an item MenuStat never weighed would be a
 * number the app invented, which is the one thing this corpus must not do.
 */
export function toServings(item: IndexedMenuItem): MenuStatServingOption[] {
  const servings: MenuStatServingOption[] = [
    {
      label: item.label,
      grams: item.grams,
      kcal: item.kcal,
      protein: item.protein,
      ...(item.carb !== undefined ? { carbs: item.carb } : {}),
      ...(item.fat !== undefined ? { fat: item.fat } : {}),
      kind: "portion",
    },
  ];

  if (item.grams > 0) {
    const r = 100 / item.grams;
    servings.push({
      label: "100 g",
      grams: 100,
      kcal: Math.round(item.kcal * r),
      protein: Math.round(item.protein * r),
      ...(item.carb !== undefined ? { carbs: Math.round(item.carb * r) } : {}),
      ...(item.fat !== undefined ? { fat: Math.round(item.fat * r) } : {}),
      kind: "per100g",
    });
  }

  return servings;
}

function toHit(item: IndexedMenuItem, year: number): MenuStatHit {
  return {
    source: "menu",
    id: item.id,
    description: item.desc.slice(0, MAX_DESCRIPTION),
    brand: item.chain,
    // Carries the snapshot year so the client can say "Chili's · 2022 menu"
    // rather than implying the figure is current. ADR-0027: the data must not
    // be able to lie about its own age.
    dataType: `restaurant_menu_${year}`,
    servings: toServings(item),
  };
}

/**
 * Search the bundled restaurant dataset.
 *
 * Returns at most `limit` hits, best first. When the query names a chain, ONLY
 * that chain's items are considered — the caller (`searchFoods`) uses that
 * signal to give restaurant results the whole page, because someone who typed
 * "olive garden" is not looking for a USDA entry on olives.
 */
export function searchMenuStat(index: MenuStatIndex, query: string, limit: number): MenuStatHit[] {
  const queryWords = words(query);
  if (!queryWords.length) return [];

  const matched = matchChain(index, queryWords);
  const tokens = matched ? matched.rest : queryWords;
  const namedChain = matched?.chain ?? null;

  const scored: { item: IndexedMenuItem; score: number }[] = [];
  for (const item of index.items) {
    const score = scoreItem(item, tokens, namedChain);
    if (score !== null) scored.push({ item, score });
  }

  scored.sort((a, b) => b.score - a.score || a.item.desc.localeCompare(b.item.desc));
  return scored.slice(0, limit).map(({ item }) => toHit(item, index.year));
}

/** True when the query names one of the bundled chains — the caller's cue that
 *  restaurant results are what was asked for. */
export function queryNamesChain(index: MenuStatIndex, query: string): boolean {
  return matchChain(index, words(query)) !== null;
}

/** Resolve one item by id, for `getFoodDetail` with `source: 'menu'`. */
export function menuStatDetail(index: MenuStatIndex, id: string): MenuStatDetail | null {
  const item = index.items.find((i) => i.id === id);
  if (!item) return null;
  return {
    source: "menu",
    id: item.id,
    description: item.desc.slice(0, MAX_DESCRIPTION),
    brand: item.chain,
    servings: toServings(item),
  };
}
