/**
 * Bundled USDA food database — search + detail, with no network call.
 *
 * Backs `searchFoods` / `getFoodDetail` in place of the live FoodData Central
 * API. The dataset (`functions/data/usda-foods.json`, ~3.6 MB, 13,272 foods) is
 * generated by `scripts/ingest-usda.mjs` from three CC0 USDA datasets and
 * committed, so a deploy carries its own data and a search costs nothing:
 * no API key, no 1,000 req/hour ceiling, no upstream outage to degrade around.
 *
 * Everything here is pure apart from {@link loadFoods}, which reads the JSON
 * once per instance — so the ranking and the detail mapping are unit-testable
 * without an emulator, which is the entire reason they live in their own module
 * rather than inside the callables.
 *
 * WIRE CONTRACT: `FoodSearchHit` / `ServingOption` / `FoodDetail` are the shapes
 * defined in `./food-search.ts`, which mirrors `packages/core/src/food-search.ts`
 * by hand. This module produces those shapes and must not diverge from them.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";

/** One food as emitted by the ingest. Macros are per 100 g. */
export interface UsdaFood {
  id: string;
  desc: string;
  dataType: string;
  per100: { kcal: number; protein: number; carb: number; fat: number };
  portions: { label: string; grams: number }[];
}

/** A food plus the lowercased forms the matcher needs, computed once at load.
 *  Exported because `photo-resolve.ts` ranks against the same index — it reuses
 *  {@link scoreFood} rather than growing a second, drifting copy of the rules. */
export interface IndexedFood extends UsdaFood {
  norm: string;
  words: string[];
  /** Singular-folded words, so "carrot" matches "Carrots, raw". */
  wordStems: string[];
  /** Comma-delimited descriptor segments: "Fish, tuna, raw" → [fish, tuna, raw]. */
  segments: string[];
  /** The same segments as singular-folded words, for the leading-segment cover test. */
  segmentStems: string[][];
}

export interface UsdaSearchHit {
  source: "fdc";
  id: string;
  description: string;
  dataType: string;
}

export interface UsdaServingOption {
  label: string;
  grams: number;
  kcal: number;
  protein: number;
  carbs?: number;
  fat?: number;
  kind: "per100g" | "portion";
}

export interface UsdaDetail {
  source: "fdc";
  id: string;
  description: string;
  servings: UsdaServingOption[];
}

/**
 * Data-quality nudge, deliberately tiny. Lab grade tells you how accurate a
 * number is, NOT whether it is the food the user meant — an early revision gave
 * Foundation a large bonus and "egg" returned "Egg, yolk, dried" (654 kcal)
 * ahead of "Egg, whole, raw". Quality decides the MACROS, at ingest time, where
 * Foundation overrides SR on a description clash; relevance decides the ORDER,
 * here. Keep these small enough that any real text signal outranks them.
 */
const DATA_TYPE_BONUS: Record<string, number> = {
  foundation_food: 4,
  sr_legacy_food: 2,
  survey_fndds_food: 2,
};

/**
 * Survey qualifiers: "NFS" = not further specified, and the "skin eaten"
 * family. Legitimate rows, poor search results — someone typing "milk" wants
 * "Milk, whole", not "Milk, NFS". Demoted, never excluded.
 */
const VAGUE_MARKERS =
  /\b(nfs|ns as to|not further specified|not specified|skin (not )?eaten)\b/;

/**
 * USDA writes a canonical food as a comma-delimited descriptor list whose
 * qualifiers narrow the plain form ("Egg, whole, raw"). These three patterns
 * separate that plain form from its neighbours in the same list:
 *
 *  PLAIN      — the unprocessed default a bare query almost always means.
 *  PROCESSED  — a derived or prepared form ("Apple, dried" for "apple").
 *  COMPOSITE  — a multi-ingredient dish. Connectives are the giveaway: real
 *               foods use commas, dishes use "with"/"and"/"or" ("Tuna with
 *               cream or white sauce"). This is what keeps a bare ingredient
 *               query off the recipes that merely mention it.
 */
const PLAIN = /\b(raw|whole|plain|unprepared)\b/;
const PROCESSED =
  /\b(dried|dehydrated|powder|powdered|concentrate|canned|frozen|fried|breaded|sweetened|jerky|chips|candied|salad|sandwich|burrito|casserole|soup|dip|pie|cake|patty|roll)\b/g;
const COMPOSITE = /\b(with|and|or)\b/g;

const MAX_DESCRIPTION = 140;
const MAX_SERVINGS = 12;

let cache: IndexedFood[] | null = null;

/** Split into lowercase alphanumeric words — the unit both sides match on.
 *  Exported as `wordsOf` so the photo resolver tokenizes model phrases exactly
 *  the way descriptions were tokenized at index time. */
export function words(s: string): string[] {
  return s.toLowerCase().split(/[^a-z0-9.]+/i).filter(Boolean);
}

/**
 * Fold a trailing plural "s", so a query matches USDA's spelling of the food.
 *
 * People type "carrot" and "onion"; USDA files "Carrots, raw" and "Onions,
 * raw". Without this the singular only matched as a word *prefix*, which scores
 * far lower than an exact segment — so "carrot" returned "Carrot, dehydrated"
 * and "onion" returned "Bread, onion", both beaten by the plural they meant.
 *
 * Deliberately not a real stemmer: a Porter-style one would also fold
 * "raw"/"raws" and conflate distinct foods. Length and "ss" guards keep
 * "oats"→"oat" working while leaving "molasses" and "gas" alone.
 */
export function stem(w: string): string {
  if (w.length > 4 && w.endsWith("ies")) return `${w.slice(0, -3)}y`;   // blueberries → blueberry
  if (w.length > 4 && w.endsWith("oes")) return w.slice(0, -2);         // tomatoes → tomato
  if (w.length > 4 && /(?:s|x|z|ch|sh)es$/.test(w)) return w.slice(0, -2); // peaches → peach
  if (w.length > 3 && w.endsWith("s") && !w.endsWith("ss")) return w.slice(0, -1);
  return w;
}

function stems(list: string[]): string[] {
  return list.map(stem);
}

export function normalizeQuery(q: string): string {
  return q.trim().toLowerCase().replace(/\s+/g, " ");
}

/** Index raw ingest records for matching. Exported for tests. */
export function indexFoods(foods: UsdaFood[]): IndexedFood[] {
  return foods.map((f) => {
    const norm = f.desc.toLowerCase();
    return {
      ...f,
      norm,
      words: words(f.desc),
      wordStems: stems(words(f.desc)),
      segments: norm.split(",").map((s) => s.trim()),
      segmentStems: norm.split(",").map((s) => stems(words(s))),
    };
  });
}

/**
 * Load and index the bundled dataset, once per function instance (~45 ms parse
 * on a cold start, then free). `__dirname` is `functions/lib` after tsc, so the
 * data sits one level up.
 */
export function loadFoods(dataPath = join(__dirname, "../data/usda-foods.json")): IndexedFood[] {
  if (!cache) {
    cache = indexFoods(JSON.parse(readFileSync(dataPath, "utf8")) as UsdaFood[]);
  }
  return cache;
}

/** Test seam: drop the memoized dataset. */
export function resetCache(): void {
  cache = null;
}

/**
 * Score one food against the query tokens, or null when it doesn't match.
 *
 * Every token must appear somewhere, so "chicken breast" can't match a food
 * that only mentions chicken. Beyond that the score rewards *how* each token
 * matched — a whole word beats a word prefix beats a mid-word substring — then
 * favours short, plainly-named entries, which are the generic foods a person
 * searching a bare term almost always wants.
 */
export interface ScoreOptions {
  /**
   * Processed/composite words the QUERY itself used, whose penalty should be
   * waived for a food that contains them. Typeahead leaves this empty — someone
   * typing "plantain" wants the raw one. The photo resolver passes the model's
   * preparation words, because "fried plantains" is describing tostones and
   * penalising "Plantains, fried" would return the food it explicitly is not.
   */
  waiveProcessed?: string[];
  /** Whether the PLAIN bonus applies. Off when the query names a preparation,
   *  so "grilled chicken" is not pulled toward "raw". Defaults to on. */
  plainBonus?: boolean;
}

export function scoreFood(
  food: IndexedFood,
  tokens: string[],
  query: string,
  opts: ScoreOptions = {},
): number | null {
  let score = 0;
  for (const t of tokens) {
    const s = stem(t);
    if (food.wordStems.includes(s)) score += 30;
    else if (food.wordStems.some((w) => w.startsWith(s))) score += 20;
    else if (food.norm.includes(t)) score += 5;
    else return null;
  }

  score += headMatchBonus(food, tokens, query);

  // Prefer concise names: "Bananas, raw" over "Babyfood, bananas with tapioca".
  score += Math.max(0, 70 - food.desc.length) / 3;
  // Flat, NOT per match: counting them ranked "Onions, frozen, whole,
  // unprepared" (two plain words) above "Onions, red, raw" (one). Being plain
  // is a property of the food, not a quantity.
  if ((opts.plainBonus ?? true) && PLAIN.test(food.norm)) score += 12;
  score -= 18 * countMatches(food.norm, PROCESSED, opts.waiveProcessed);
  score -= 25 * countMatches(food.norm, COMPOSITE, opts.waiveProcessed);
  score += DATA_TYPE_BONUS[food.dataType] ?? 0;
  if (VAGUE_MARKERS.test(food.norm)) score -= 25;

  return score;
}

/** Count regex hits, minus any the caller asked to forgive (see ScoreOptions). */
function countMatches(s: string, re: RegExp, waive?: string[]): number {
  const hits = s.match(re) ?? [];
  if (!waive?.length) return hits.length;
  const forgiven = new Set(waive.map((w) => w.toLowerCase()));
  return hits.filter((h) => !forgiven.has(h.toLowerCase())).length;
}

/**
 * Reward a food whose descriptor list is *headed* by what was asked for.
 *
 * Two facts about USDA naming make this the strongest relevance signal here:
 *
 *  1. It inverts English compounds — "cheddar cheese" is filed as "Cheese,
 *     cheddar", "ground beef" as "Beef, ground, raw". So the head is usually
 *     the query's LAST token, not its first.
 *  2. It files some foods under a genus — "Fish, tuna, light, canned in
 *     water". So the match can be the second segment rather than the first.
 *
 * Scoring the earliest segment that matches, and decaying by position, covers
 * both without special-casing either. Without it, "tuna" returns "Tuna salad
 * sandwich wrap" — which leads with the literal word and is the wrong food.
 *
 * **Matching the WHOLE query outranks matching only its head**, and the gap has
 * to be wide enough that brevity cannot close it. It used to be zero: a food
 * whose leading segments spelled out the entire query and one that merely shared
 * the query's last token both scored 150, so the shorter description won. That
 * is how "tomato sauce" returned **"Sauce, steak, tomato based"** (95 kcal/100 g)
 * instead of "Tomato sauce, canned" (24) — the head token was "sauce", steak
 * sauce is a sauce, and its name is 9 characters shorter. Found on a real
 * production photo scan, not in a test.
 *
 * For a single-token query the two are the same match, so nothing changes there.
 */
function headMatchBonus(food: IndexedFood, tokens: string[], query: string): number {
  if (food.norm === query) return 1000;
  if (leadingSegmentsCover(food, tokens)) return 200;

  // Compared as stems so "onion" still matches the segment "onions".
  const queryStem = stems(tokens).join(" ");
  const headStem = stem(tokens[tokens.length - 1]);
  const limit = Math.min(food.segments.length, 3);
  for (let i = 0; i < limit; i++) {
    const seg = food.segmentStems[i].join(" ");
    // The segment IS the whole query — as specific as a leading-segment cover.
    if (seg === queryStem) return 200 - 30 * i;
    // Only the head noun matched. Real, but weaker: every sauce matches "sauce".
    if (seg === headStem) return 120 - 30 * i;
  }

  if (food.norm.startsWith(query)) return 60;
  if (food.norm.includes(query)) return 20;
  return 0;
}

/**
 * True when the leading segments spell out exactly the query and nothing more —
 * "chicken breast" against "Chicken, breast, boneless, skinless, raw".
 *
 * USDA writes the same food two ways: as a compound head ("Chicken breast,
 * oven-roasted, sliced") or spread across leading segments ("Chicken, breast,
 * …"). Scoring them equally is the point. Ranking the compound higher put deli
 * slices above actual chicken breast, because only the spelling differed — with
 * both at 150 the plain/processed signals decide, which is what should decide.
 *
 * Order-insensitive, since USDA inverts compounds: "cheddar cheese" is filed as
 * "Cheese, cheddar".
 */
function leadingSegmentsCover(food: IndexedFood, tokens: string[]): boolean {
  const target = stems(tokens).sort().join(" ");
  const acc: string[] = [];
  const limit = Math.min(food.segmentStems.length, 3);
  for (let i = 0; i < limit; i++) {
    acc.push(...food.segmentStems[i]);
    if (acc.length > tokens.length) return false;
    if (acc.length === tokens.length && [...acc].sort().join(" ") === target) return true;
  }
  return false;
}

/**
 * Rank the bundled dataset against a typeahead query.
 *
 * Ties break on description length then id so the ordering is total and stable
 * — two ingests of the same data return results in the same order, which is
 * what makes the output testable at all.
 */
export function searchUsda(foods: IndexedFood[], rawQuery: string, size: number): UsdaSearchHit[] {
  const query = normalizeQuery(rawQuery);
  const tokens = words(query);
  if (tokens.length === 0) return [];

  const scored: { food: IndexedFood; score: number }[] = [];
  for (const food of foods) {
    const score = scoreFood(food, tokens, query);
    if (score !== null) scored.push({ food, score });
  }

  scored.sort(
    (a, b) =>
      b.score - a.score ||
      a.food.desc.length - b.food.desc.length ||
      a.food.id.localeCompare(b.food.id),
  );

  return scored.slice(0, size).map(({ food }) => ({
    source: "fdc" as const,
    id: food.id,
    description: food.desc.slice(0, MAX_DESCRIPTION),
    dataType: food.dataType,
  }));
}

/** Look up one food by its FDC id. */
export function findById(foods: IndexedFood[], id: string): IndexedFood | undefined {
  return foods.find((f) => f.id === id);
}

/**
 * Build the portion picker for a food: the canonical per-100 g row plus each
 * household measure, with macros pre-scaled so the client only picks a row.
 *
 * Mirrors the FDC-API `buildServings()` it replaces — same rounding, same
 * "(148 g)" label suffix, same 12-row cap — so a client cannot tell which
 * backend answered.
 */
export function buildUsdaDetail(food: UsdaFood): UsdaDetail {
  const { kcal, protein, carb, fat } = food.per100;
  const at = (ratio: number): UsdaServingOption => ({
    label: "",
    grams: 0,
    kcal: Math.round(kcal * ratio),
    protein: Math.round(protein * ratio),
    carbs: Math.round(carb * ratio),
    fat: Math.round(fat * ratio),
    kind: "portion",
  });

  const servings: UsdaServingOption[] = [
    { ...at(1), label: "100 g", grams: 100, kind: "per100g" },
  ];

  for (const p of food.portions) {
    if (!(p.grams > 0)) continue;
    servings.push({
      ...at(p.grams / 100),
      label: `${p.label} (${Math.round(p.grams)} g)`.slice(0, 80),
      grams: p.grams,
    });
  }

  const seen = new Set<string>();
  const deduped: UsdaServingOption[] = [];
  for (const s of servings) {
    if (seen.has(s.label)) continue;
    seen.add(s.label);
    deduped.push(s);
    if (deduped.length >= MAX_SERVINGS) break;
  }
  return {
    source: "fdc",
    id: food.id,
    description: food.desc.slice(0, MAX_DESCRIPTION),
    servings: deduped,
  };
}
