import { readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * The Siri phrases and their es-PR translations describe the same set.
 *
 * App Shortcut phrases are the one user-facing string in this app that cannot go
 * through `src/i18n/` — Siri resolves them before any of our code runs, so they
 * live in `AppShortcuts.strings` bundle resources generated by
 * `plugins/withAppShortcutsLocalization.js`.
 *
 * That puts them outside the doctor's 642-key EN/es-PR parity check, which is
 * how they stayed English-only in an app whose market is Puerto Rico. This is
 * their parity check.
 *
 * **The keys must match the Swift byte for byte.** A mismatch does not warn and
 * does not fail a build; the phrase simply stays English on a Spanish phone, and
 * a phrase that exists in the plugin but not in Swift is dead weight nobody will
 * ever notice. Both directions are checked.
 */

const ROOT = join(__dirname, '..', '..');
const SWIFT = readFileSync(join(ROOT, 'targets', '_shared', 'QuickAddIntents.swift'), 'utf8');

// eslint-disable-next-line @typescript-eslint/no-var-requires
const plugin = readFileSync(join(ROOT, 'plugins', 'withAppShortcutsLocalization.js'), 'utf8');

/**
 * The phrase templates as `AppShortcuts.strings` spells them: `\(.applicationName)`
 * becomes `${applicationName}`, `\(\.$preset)` becomes `${preset}`.
 */
function swiftPhrases(): string[] {
  const block = /static var appShortcuts: \[AppShortcut\] \{([\s\S]*)\n\}/.exec(SWIFT)?.[1] ?? '';
  return [...block.matchAll(/"([^"]*\\\([^"]*)"/g)]
    .map((m) => m[1])
    .map((p) =>
      p
        .replace(/\\\(\.applicationName\)/g, '${applicationName}')
        .replace(/\\\(\\\.\$(\w+)\)/g, '${$1}'),
    );
}

/** The keys of the PHRASES map in the plugin. */
function pluginKeys(): string[] {
  const block = /const PHRASES = \{([\s\S]*?)\n\};/.exec(plugin)?.[1] ?? '';
  return [...block.matchAll(/^\s*'([^']+)':/gm)].map((m) => m[1]);
}

describe('Siri phrase localisation', () => {
  it('finds phrases in both places at all', () => {
    // Guards the regexes themselves: if either stops matching, every assertion
    // below passes vacuously, which is the failure mode of a text-based test.
    expect(swiftPhrases().length).toBeGreaterThanOrEqual(8);
    expect(pluginKeys().length).toBeGreaterThanOrEqual(8);
  });

  it('translates every phrase the provider declares', () => {
    const missing = swiftPhrases().filter((p) => !pluginKeys().includes(p));
    expect(missing).toEqual([]);
  });

  it('declares no translation for a phrase that does not exist', () => {
    const orphans = pluginKeys().filter((k) => !swiftPhrases().includes(k));
    expect(orphans).toEqual([]);
  });

  it('keeps ${applicationName} in every English key AND every Spanish value', () => {
    // Apple rejects an AppShortcutsProvider whose phrases omit the app name, and
    // it applies to the translation exactly as to the original.
    const pairs = [...plugin.matchAll(/^\s*'([^']+)':\s*'([^']+)',$/gm)];
    expect(pairs.length).toBeGreaterThanOrEqual(8);
    for (const [, en, es] of pairs) {
      expect(en).toContain('${applicationName}');
      expect(es).toContain('${applicationName}');
    }
  });

  it('keeps the parameter token identical on both sides of a translation', () => {
    // `${preset}` names the intent's parameter. Translating the token itself
    // silently unbinds the phrase from the parameter.
    const pairs = [...plugin.matchAll(/^\s*'([^']+)':\s*'([^']+)',$/gm)];
    for (const [, en, es] of pairs) {
      const tokens = (s: string) => (s.match(/\$\{\w+\}/g) ?? []).sort();
      expect(tokens(es)).toEqual(tokens(en));
    }
  });

  it('is actually registered in app.json, or none of it ships', () => {
    const appJson = JSON.parse(readFileSync(join(ROOT, 'app.json'), 'utf8'));
    expect(appJson.expo.plugins).toContain('./plugins/withAppShortcutsLocalization');
  });
});
