const { IOSConfig, withDangerousMod, withInfoPlist, withXcodeProject } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Localises the Siri phrases (`AppShortcutsProvider`) into es-PR.
 *
 * ## Why this needs a plugin at all
 *
 * App Shortcut phrases are the one string in this app that **cannot** go through
 * our own i18n. Siri resolves them before any of our code runs — there is no
 * React, no `useT`, no profile to read a locale from — so the translations have
 * to be bundle resources iOS can read on its own: `AppShortcuts.strings`, one
 * per `.lproj`, in the **app** target.
 *
 * Nothing in the managed workflow puts arbitrary `.lproj` resources into the app
 * target, and `@bacons/apple-targets` only reaches the extension targets. Hence
 * a config plugin.
 *
 * ## The gap this closes
 *
 * `npm run doctor` enforces 642-key EN/es-PR parity in `src/i18n/`, and every
 * user-facing string in both apps honours it — while the Siri phrases were
 * English-only, in an app whose market is Puerto Rico. Being English-only is not
 * cosmetic here: a phone set to Spanish resolves Spanish phrases, so *"registra
 * mi batida en Ignia"* matched nothing at all.
 *
 * ## Three rules the file format imposes
 *
 * 1. **Every phrase must contain `${applicationName}`.** Apple rejects a
 *    provider whose phrases omit it, in the translation exactly as in the Swift.
 * 2. **The key is the English phrase**, written with `${applicationName}` and
 *    `${parameterName}` where the Swift has `\(.applicationName)` and
 *    `\(\.$preset)`.
 * 3. **Keys must match the Swift byte for byte.** A typo does not warn; that
 *    phrase simply stays English. `src/__tests__/siri-phrases-parity.test.ts`
 *    diffs the two.
 *
 * `CFBundleLocalizations` is set alongside, because the app declared **no**
 * localisations at all — without it iOS never looks in `es-PR.lproj`, and the
 * strings file would ship inert.
 */

/** Keys are the English phrases, verbatim from `_shared/QuickAddIntents.swift`. */
const PHRASES = {
  'Log a preset in ${applicationName}': 'Registra un preset en ${applicationName}',
  'Log my preset in ${applicationName}': 'Registra mi preset en ${applicationName}',
  'Quick add in ${applicationName}': 'Añade rápido en ${applicationName}',
  'Log ${preset} in ${applicationName}': 'Registra ${preset} en ${applicationName}',
  'Log my ${preset} in ${applicationName}': 'Registra mi ${preset} en ${applicationName}',
  'Add ${preset} to ${applicationName}': 'Añade ${preset} a ${applicationName}',
  'Log calories in ${applicationName}': 'Registra calorías en ${applicationName}',
  'Add calories to ${applicationName}': 'Añade calorías a ${applicationName}',
};

const LOCALES = ['en', 'es-PR'];
const FILENAME = 'AppShortcuts.strings';

/** `.strings` is one `"key" = "value";` per line, UTF-8. */
function serialize(locale) {
  const header = [
    '/* Siri phrases for IgniaShortcuts (AppShortcutsProvider).',
    '   GENERATED by plugins/withAppShortcutsLocalization.js — edit that, not this.',
    '   Keys must match targets/_shared/QuickAddIntents.swift byte for byte. */',
    '',
  ].join('\n');
  const body = Object.entries(PHRASES)
    .map(([en, es]) => `"${en}" = "${locale === 'en' ? en : es}";`)
    .join('\n');
  return `${header}${body}\n`;
}

module.exports = function withAppShortcutsLocalization(config) {
  // 1. Declare the localisations, or iOS never looks in `es-PR.lproj`.
  config = withInfoPlist(config, (cfg) => {
    cfg.modResults.CFBundleLocalizations = LOCALES;
    // The phrases are authored in English; anything unmatched falls back here.
    cfg.modResults.CFBundleDevelopmentRegion = 'en';
    return cfg;
  });

  // 2. Write the `.lproj` files into the generated project.
  config = withDangerousMod(config, [
    'ios',
    (cfg) => {
      const projectRoot = path.join(
        cfg.modRequest.platformProjectRoot,
        cfg.modRequest.projectName,
      );
      for (const locale of LOCALES) {
        const dir = path.join(projectRoot, `${locale}.lproj`);
        fs.mkdirSync(dir, { recursive: true });
        fs.writeFileSync(path.join(dir, FILENAME), serialize(locale), 'utf8');
      }
      return cfg;
    },
  ]);

  // 3. Add them to the app target's Copy Bundle Resources. Xcode preserves the
  //    `.lproj` segment of a resource's path, which is what makes the bundle
  //    layout iOS expects.
  return withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;
    const groupName = cfg.modRequest.projectName;
    for (const locale of LOCALES) {
      // Relative to `ios/`, NOT to the group's folder. Passing the bare
      // `en.lproj/AppShortcuts.strings` makes Xcode look in `ios/` and fail the
      // build with "Build input file cannot be found" — which is how build 33
      // died. The group name is the same path segment the files were written
      // under in the dangerous mod above.
      const filepath = `${groupName}/${locale}.lproj/${FILENAME}`;
      // Idempotent: prebuild can run repeatedly, and a duplicated build file
      // makes Xcode fail with "multiple commands produce".
      if (project.hasFile(filepath)) continue;
      IOSConfig.XcodeUtils.addResourceFileToGroup({
        filepath,
        groupName,
        project,
        isBuildFile: true,
      });
    }
    return cfg;
  });
};
